kind: pipeline
workspace:
  base: /go
  path: github.com/82253452/weixin-message
name: drone
steps:
  - name: test
    value: 114.114.114.114
    image: golang
    custom_dns: [ 114.114.114.114 ]
    commands:
      - pwd
      - ls
      - go get
      - go build


