kind: pipeline
workspace:
  base: /go
  path: github.com/82253452/weixin-message
name: drone
steps:
  - name: docker
    image: plugins/docker
    custom_dns: [ 114.114.114.114 ]
  - name: test
    image: golang
    custom_dns: [ 114.114.114.114 ]
    commands:
      - pwd
      - ls
      - go get
      - go build


