kind: pipeline
workspace:
  base: /go
  path: github.com/82253452/weixin-message
name: drone

steps:
  - name: test
    image: golang
    commands:
      - pwd
      - ls
      - go get
      - go build


