kind: pipeline
workspace:
  base: /go
  path: src/weixin
name: drone
steps:
  - name: install
    value: 114.114.114.114
    image: golang
    custom_dns: [ 114.114.114.114 ]
    commands:
      - cd ../
      - mkdir -p golang.org/x
      - cd golang.org/x
      - git clone https://github.com/golang/sys.git
      - cd /go/src/weixin
      - bash
      - cd src
      - pwd
      - go get
      - go build

  - name: build
    image: plugins/docker
    repo: test/test
    dockerfile: ./Dockerfile
    tags: 1


