kind: pipeline
workspace:
  base: /go
  path: src/weixin
name: drone
steps:
  - name: test
    value: 114.114.114.114
    image: golang
    custom_dns: [ 114.114.114.114 ]
    commands:
      - cd ../
      - mkdir -p golang.org/x
      - cd golang.org/x
      - git clone https://github.com/golang/sys.git
      - bash
      - cd src
      - pwd
      - ls
      - go get
      - go build


